name: Lint commit and code

on:
  push:
  pull_request:
  merge_group:

permissions: {}

jobs:
  commitlint:
    name: Ensure PR has one commit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if the pull request contains a single commit
        if: github.event_name == 'pull_request'
        run: |
          commit_count="${{ github.event.pull_request.commits }}"

          if [ -z "$commit_count" ]; then
            echo "[ERROR] commit_count is empty"
            exit 1
          fi

          if [ "$commit_count" -ne 1 ]; then
            echo "[ERROR] This pull request contains $commit_count commits. Please squash to a single commit."
            exit 1
          else
            echo "
          fi

  superlinter:
    name: Run Super Linter
    runs-on: ubuntu-latest
    needs: commitlint # Only run if commitlint succeeds
    permissions:
      contents: read
      statuses: write
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true # Optional: Set to false to only lint changed files
